formation_distances: [[0.00, 1.81, 2.91, 2.98, 1.76],[1.81, 0.00, 2.07, 2.96, 2.95],[2.91, 2.07, 0.00, 1.36, 2.75],[2.98, 2.96, 1.36, 0.00, 1.99],[1.76, 2.95, 2.75, 1.99, 0.00]]
# want to remove the need for robot_numbers
# This is a Pentagon
#
#         #
#             
#   #           #
#             
#       #     #