/**:
  ros__parameters:
    robot:
      neighborhood_mode: "global" 
      neighborhood_global: [
        0, 0, 1, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 1, 1, 1, 0, 0,
        1, 1, 1, 0, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 1, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 0
        ]
      neighborhood_size: 9
      neighborhood_default: 0     # if outside the span, 1 means they are a neighbor and 0 means they are not

    logging:
      enabled: true

    neighbor:
      avoid: true
      walk_around: false